# Generated by Django 4.1.4 on 2022-12-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_food', models.CharField(max_length=200, verbose_name='Name')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('date', models.DateField()),
            ],
        ),
    ]
