# Generated by Django 4.1.4 on 2023-01-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='juin', verbose_name='Date')),
                ('_name', models.CharField(max_length=200, verbose_name='Food Name')),
                ('quantity_eaten', models.IntegerField(verbose_name='Quantity')),
                ('q_water', models.CharField(max_length=10, verbose_name='Quantity Water')),
                ('q_other_liquid', models.CharField(max_length=10, verbose_name='Quantity Other Liquid')),
                ('fruit', models.CharField(max_length=50, verbose_name='Frutis eaten')),
                ('sport', models.IntegerField(verbose_name='Sport Time')),
                ('health_problem', models.CharField(max_length=100, verbose_name='Health Problem')),
            ],
        ),
    ]
