# Generated by Django 4.1.4 on 2023-01-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodAgenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
