# Generated by Django 4.1.4 on 2023-01-03 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodAgenda', '0003_day_remove_food_date_food_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='day',
            name='jour',
        ),
        migrations.AddField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 12, 4, 45, 537664)),
        ),
    ]
