# Generated by Django 4.1.4 on 2023-01-03 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodAgenda', '0004_remove_day_annee_remove_day_jour_day_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 12, 7, 54, 37665, tzinfo=datetime.timezone.utc)),
        ),
    ]
